org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21
minecraft_version_range=[1.21.0,1.22)

neo_version=21.0.143
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=convenientcurioscontainer
mod_name=Convenient Curios Container
mod_version=2.1
mod_license=LGPL-3.0
mod_group_id=com.leobeliik
mod_authors=LeoBeliik
mod_description=A convenient way to store your trinkets!\nThis mod adds an item that allows you to store items that use the Curios API and let you equip / unequip them easily.
mod_display_url=https://github.com/LeoBeliik/ConvenientCuriosContainer
mod_logo_file=ccc_logo.png

curiosversion = 9.+