org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.0
minecraft_version_range=[1.21.0,1.22)
neo_version=21.0.109-beta
neo_version_range=[21,)
loader_version_range=[4,)
mod_id=convenientcurioscontainer
mod_name=ConvenientCuriosContainer
mod_license=LGPL-3.0
mod_version=1.17
mod_group_id=com.leobeliik
mod_authors=LeoBeliik
mod_description=A convenient way to store your trinkets! This mod adds an item that allows you to store items that use the Curios API and let you equip / unequip them easily.
curiosversion = 9.+