org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

mcversion = 1.20.1
forgeversion = 47.4.0
mapversion = 1.20.1
curiosversion = 5.+
accessories_version=1.0.0-beta.+
cclayer_version=7.4.0-beta.1+

# Mod options
mod_name=ConvenientCuriosContainer
mod_author=LeoBeliik
mod_id=convenientcurioscontainer
modversion = 1-BETA
