modLoader="javafml"
loaderVersion="${loader_version_range}"
license= "GNU LESSER GENERAL PUBLIC LICENSE"
licenseURL= "https://github.com/LeoBeliik/ConvenientCuriosContainer/blob/master/LICENSE.txt"
issueTrackerURL="https://github.com/LeoBeliik/ConvenientCuriosContainer/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
    displayURL="${mod_display_url}"
    logoFile="${mod_logo_file}"

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"





